name: Build and Push Docker Image

on:
  release:
    types:
      - created

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract Tag Name
        shell: bash
        run: echo "MLFLOW_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Image
        run: make docker-build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Push Image
        run: make docker-push